apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whatsapp-ingress
  namespace: meta-whatsapp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - meta-whatsapp.zagent.stage.yavar.ai
    secretName: whatsapp-tls
  rules:
  - host: meta-whatsapp.zagent.stage.yavar.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whatsapp-service
            port:
              number: 80